// File generated by FlutterFire CLI.
//
// ⚠️ КОНФИГУРАЦИЯ FIREBASE ТРЕБУЕТСЯ
//
// Эта заглушка позволяет приложению запуститься, но функции Firebase не работают.
//
// ИНСТРУКЦИЯ по получению реальной конфигурации:
// ==========================================
//
// 1. Откройте https://console.firebase.google.com
// 2. Выберите ваш проект (или создайте новый)
// 3. Нажмите на иконку </> (Add Firebase to your web app)
// 4. Скопируйте объект firebaseConfig:
//    const firebaseConfig = {
//      apiKey: "AIzaSyD...",
//      authDomain: "project.firebaseapp.com",
//      projectId: "project-id",
//      storageBucket: "project.appspot.com",
//      messagingSenderId: "12345...",
//      appId: "1:12345..."
//    };
//
// 5. Заполните значения в классах ниже
// 6. Перезагрузите приложение (R в консоли Flutter)
//
// ИЛИ запустите команду:
// flutterfire configure --project=YOUR_PROJECT_ID

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Используем веб-конфигурацию на всех платформах для разработки
    return web;
  }

  // ЗАМЕНИТЕ ПУСТЫЕ ЗНАЧЕНИЯ НА РЕАЛЬНЫЕ ИЗ FIREBASE CONSOLE
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL42cbAAMvVLSIwNrUTsFxmxW7PWTn3kc',
    appId: '1:166885500146:web:c6f73603fc8fdbb8489c6b',
    messagingSenderId: '166885500146',
    projectId: 'lumi-d0e60',
    authDomain: 'lumi-d0e60.firebaseapp.com',
    storageBucket: 'lumi-d0e60.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_xxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:android:xxxxxxxxxxxxxxxx',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_xxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:ios:xxxxxxxxxxxxxxxx',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
    iosBundleId: 'com.example.lumi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_xxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:macos:xxxxxxxxxxxxxxxx',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
    iosBundleId: 'com.example.lumi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_xxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:web:xxxxxxxxxxxxxxxx',
    messagingSenderId: '123456789',
    projectId: 'your-project-id',
  );
}
